{
 "title": "Access Logs: Errors",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "default" },
   {
    "name": "app",
    "query": "nginx, frontend, public-api, product-api, payments, product-db, traffic"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "504" }
  ]
 },
 "panels": [
  {
   "title": "Total count of logs in \"$namespace\" namespace",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"consul-dataplane\",namespace=~\"$namespace\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total count of logs containing \"$searchable_pattern\" in \"$namespace\" namespace",
   "type": "stat",
   "description": "Total Count of $searchable_pattern in the specified time range",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"consul-dataplane\",namespace=~\"$namespace\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Total count of logs containing \"$searchable_pattern\" count by app",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"consul-dataplane\", namespace=~\"$namespace\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (app)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of logs containing \"$searchable_pattern\" per app",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(({container=\"consul-dataplane\",namespace=~\"$namespace\"} |~ \"(?i)$searchable_pattern\")[30s])) by (app)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total count of stderr / stdout in \"$namespace\" namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"consul-dataplane\", namespace=\"$namespace\"})[$__interval])) by (stream)",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Percentage of logs containing \"$searchable_pattern\" in \"$namespace\" namespace",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"consul-dataplane\",namespace=~\"$namespace\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({ container=\"consul-dataplane\", namespace=~\"$namespace\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "HTTP Method Distribution in \"$namespace\" namespace",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({container=\"consul-dataplane\", namespace=\"$namespace\"} | json | __error__=`` [$__range]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Response Code Distribution in \"$namespace\" namespace",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(response_code) (count_over_time({container=\"consul-dataplane\", namespace=\"$namespace\"} | json | __error__=`` [$__range]))",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "User Agent Distribution in \"$namespace\" namespace",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(user_agent) (count_over_time({container=\"consul-dataplane\", namespace=\"$namespace\"} | json | __error__=`` [$__range]))",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "HTTP Method Distribution in \"$namespace\" namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({container=\"consul-dataplane\", namespace=\"$namespace\"} | json | __error__=`` [$__range]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Response Code Distribution in \"$namespace\" namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "sum by(response_code) (count_over_time({container=\"consul-dataplane\", namespace=\"$namespace\"} | json | __error__=`` [$__range]))",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Response Code Distribution in \"$namespace\" namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by(user_agent) (count_over_time({container=\"consul-dataplane\", namespace=\"$namespace\"} | json | __error__=`` [$__range]))",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "Raw proxy access logs in \"$namespace\" namespace",
   "type": "logs",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{container=\"consul-dataplane\", namespace=\"$namespace\"} |= `` | json |= `\"response_code\":` |= `$searchable_pattern` "
    }
   ]
  }
 ]
}