{
 "title": "Access Logs: Events & Errors",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "default" },
   {
    "name": "app",
    "query": "nginx, frontend, public-api, product-api, payments, product-db, traffic"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Total logs over [$__interval]",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"consul-dataplane\",namespace=~\"$namespace\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total logs containing \"$searchable_pattern\" over [$__interval]",
   "type": "stat",
   "description": "Total Count of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"consul-dataplane\", namespace=~\"$namespace\"} |~ `(?i)(?i)$searchable_pattern` [$__interval]))"
    }
   ]
  },
  {
   "title": "Percentage of logs containing \"$searchable_pattern\" over  [$__interval]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time({container=\"consul-dataplane\", namespace=~\"$namespace\"} |~ `(?i)(?i)$searchable_pattern` [$__interval])) * 100) / sum(count_over_time({container=\"consul-dataplane\", namespace=~\"$namespace\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Response code distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(response_code) (count_over_time({container=\"consul-dataplane\", namespace=\"$namespace\"} | json | response_code != `0` | __error__=`` [$__range]))",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Total logs containing \"$searchable_pattern\" by app",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({container=\"consul-dataplane\", namespace=~\"$namespace\"} |~ `(?i)(?i)$searchable_pattern` [$__interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of logs containing \"$searchable_pattern\" per app",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(app) (rate({container=\"consul-dataplane\", namespace=~\"$namespace\"} |~ `(?i)(?i)$searchable_pattern` [$__range]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total bytes sent",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({container=\"consul-dataplane\", namespace=\"$namespace\"} | json | response_code = `200` | __error__=`` [$__interval]))\n",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "HTTP method distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({container=\"consul-dataplane\", namespace=\"$namespace\"} | json | method != `` | __error__=`` [$__range]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "User agent distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(user_agent) (count_over_time({container=\"consul-dataplane\", namespace=\"$namespace\"} | json | user_agent != `` | __error__=`` [$__range]))",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "Logs containing \"$searchable_pattern\" over [$__interval]",
   "type": "logs",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{container=\"consul-dataplane\", namespace=\"$namespace\"} |= `` | json |~ `(?i)$searchable_pattern`"
    }
   ]
  },
  {
   "title": "Size of access logs by app over [$__interval]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(bytes_over_time({namespace=~\"$namespace\", container=\"consul-dataplane\"} [$__interval]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Count of access logs by app over [$__interval]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(count_over_time({namespace=\"$namespace\", container=\"consul-dataplane\"}[$__interval]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "50th percentile of duration over [$__interval]",
   "type": "gauge",
   "description": "duration: The total duration in milliseconds of the request from the start time to the last byte out",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, {namespace=\"$namespace\", container=\"consul-dataplane\"} | json | unwrap duration | __error__=`` [$__interval]) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "99th percentile of duration over [$__interval]",
   "type": "gauge",
   "description": "duration: The total duration in milliseconds of the request from the start time to the last byte out",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(0.99, {namespace=\"$namespace\", container=\"consul-dataplane\"} | json | unwrap duration | __error__=`` [$__interval]) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Total logs by app over [$__interval]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({container=\"consul-dataplane\", namespace=~\"$namespace\"} [$__interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Path distribution in \"$namespace\"",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(path) (count_over_time({container=\"consul-dataplane\", namespace=\"$namespace\"} !~ `.ico|.svg|.css|.png|.txt|.js|.xml` | json | path != `` | __error__=`` [$__range]))",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "Log stream source distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"consul-dataplane\", namespace=\"$namespace\"})[$__interval])) by (stream)",
     "legendFormat": "{{stream}}"
    }
   ]
  }
 ]
}